Traceback (most recent call last):
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/caballero/anaconda3/envs/teaching/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
plt.style.use('seaborn-colorblind')
from sklearn.datasets import make_classification

features, class_labels = make_classification(n_samples = 1000,
                                             n_features = 3, 
                                             n_informative = 2, 
                                             n_redundant = 1, 
                                             n_clusters_per_class=1, 
                                             random_state=201)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m~/anaconda3/envs/teaching/lib/python3.12/site-packages/matplotlib/style/core.py:137[0m, in [0;36muse[0;34m(style)[0m
[1;32m    136[0m [38;5;28;01mtry[39;00m:
[0;32m--> 137[0m     style [38;5;241m=[39m [43m_rc_params_in_file[49m[43m([49m[43mstyle[49m[43m)[49m
[1;32m    138[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/envs/teaching/lib/python3.12/site-packages/matplotlib/__init__.py:866[0m, in [0;36m_rc_params_in_file[0;34m(fname, transform, fail_on_error)[0m
[1;32m    865[0m rc_temp [38;5;241m=[39m {}
[0;32m--> 866[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43m_open_file_or_url[49m[43m([49m[43mfname[49m[43m)[49m[43m [49m[38;5;28;43;01mas[39;49;00m[43m [49m[43mfd[49m[43m:[49m
[1;32m    867[0m [43m    [49m[38;5;28;43;01mtry[39;49;00m[43m:[49m

File [0;32m~/anaconda3/envs/teaching/lib/python3.12/contextlib.py:137[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    136[0m [38;5;28;01mtry[39;00m:
[0;32m--> 137[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    138[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:

File [0;32m~/anaconda3/envs/teaching/lib/python3.12/site-packages/matplotlib/__init__.py:843[0m, in [0;36m_open_file_or_url[0;34m(fname)[0m
[1;32m    842[0m fname [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mexpanduser(fname)
[0;32m--> 843[0m [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mutf-8[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m    844[0m     [38;5;28;01myield[39;00m f

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'seaborn-colorblind'

The above exception was the direct cause of the following exception:

[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m----> 2[0m [43mplt[49m[38;5;241;43m.[39;49m[43mstyle[49m[38;5;241;43m.[39;49m[43muse[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mseaborn-colorblind[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m make_classification
[1;32m      5[0m features, class_labels [38;5;241m=[39m make_classification(n_samples [38;5;241m=[39m [38;5;241m1000[39m,
[1;32m      6[0m                                              n_features [38;5;241m=[39m [38;5;241m3[39m, 
[1;32m      7[0m                                              n_informative [38;5;241m=[39m [38;5;241m2[39m, 
[1;32m      8[0m                                              n_redundant [38;5;241m=[39m [38;5;241m1[39m, 
[1;32m      9[0m                                              n_clusters_per_class[38;5;241m=[39m[38;5;241m1[39m, 
[1;32m     10[0m                                              random_state[38;5;241m=[39m[38;5;241m201[39m)

File [0;32m~/anaconda3/envs/teaching/lib/python3.12/site-packages/matplotlib/style/core.py:139[0m, in [0;36muse[0;34m(style)[0m
[1;32m    137[0m         style [38;5;241m=[39m _rc_params_in_file(style)
[1;32m    138[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 139[0m         [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m(
[1;32m    140[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mstyle[38;5;132;01m!r}[39;00m[38;5;124m is not a valid package style, path of style [39m[38;5;124m"[39m
[1;32m    141[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mfile, URL of style file, or library style name (library [39m[38;5;124m"[39m
[1;32m    142[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mstyles are listed in `style.available`)[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    143[0m filtered [38;5;241m=[39m {}
[1;32m    144[0m [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m style:  [38;5;66;03m# don't trigger RcParams.__getitem__('backend')[39;00m

[0;31mOSError[0m: 'seaborn-colorblind' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

